version: "3.5"
services:
  postgresql:
    image: apache/age:latest
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "cmesquita@minsait.com"
      PGADMIN_DEFAULT_PASSWORD: "123456789"
    ports:
      - "16543:80"
    depends_on:
      - postgresql
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge